services:
  - type: web
    name: lms-fullstack
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd lms_frontend
      npm install
      npm run build
      mv dist ../lms_backend/frontend_build
      cd ..
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn lms_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: ALLOWED_HOSTS
        value: "lms.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
