services:
  - type: web
    name: lms-fullstack
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd lms_frontend
      npm install
      npm run build
      cd ..
      rm -rf lms_backend/frontend_build
      cp -r lms_frontend/frontend_build lms_backend/frontend_build
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn lms_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-production-secret"
      - key: ALLOWED_HOSTS
        value: "lms1-w2jv.onrender.com"
