# Generated by Django 5.2 on 2025-06-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
